# Generated by Django 4.2.1 on 2023-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='green_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
